select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "W",  # pycodestyle warnings
    "N",  # pep8 naming
    "D419", "D300", "D301", "D419",  # pydocstyle
    "UP",  # pyupgrade
    "YTT",  # flake-2020
    "S",  #  flake8-bandit
    # "BLE",  # flake8-blind-except
    # "FBT", # flake8-boolean-trap
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "C4",  # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
    "EM",  # flake8-errmsg
    "EXE",  # flake8-executable
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "G",  # flake8-logging-format
    "INP",  # flake8-no-pep420
    "PIE",  # flake8-pie
    "T20",  # flake8-print
    "PT",  # flake8-pytest-style
    "Q",  # flake8-quotes
    "RET", # flake8-return
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    # "TCH",  # flake8-type-checking -> maybe
    # "ARG",  # flake8-unused-arguments -> No, doesn't work with pytest, django, celery...
    "PTH",  # flake8-use-pathlib
    # "ERA",  # eradicate -> No
    "PGH",  # pygrep-hooks
    "PL",  # pylint
    "TRY",  # tryceratops
    "RSE",  # flake8-raise
    "RUF",  # ruff-specific
    # "C90",  # mccabe for cyclomatic complexity -> maybe
    "I",  # isort
]

ignore = [
    "S101",  # Use of assert detected
    "PLR2004",  # Magic values are ok
]

target-version = "py311"

line-length = 100

extend-exclude = [
    ".idea",
    "migrations",
]